version: 2

builds:
  - id: linux
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X github.com/unblocked/chissl/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    overrides:
      - goos: linux
        goarch: arm
        goarm: 7
        env:
          - CC=arm-linux-gnueabihf-gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc


archives:
  - format: binary
    files:
      - none*

universal_binaries:
  - replace: true

release:
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

