version: 2

builds:
  - id: server
    main: .
    binary: chissl-server
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X github.com/unblocked/chissl/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    tags:
      - server
    overrides:
      - goos: linux
        goarch: arm
        goarm: 7
        env:
          - CC=arm-linux-gnueabihf-gcc
          - CGO_ENABLED=1
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_ENABLED=1

  - id: client
    main: .
    binary: chissl
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/unblocked/chissl/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7

archives:
  - id: server_bins
    builds:
      - server
    format: binary
    files:
      - none*
  - id: homebrew
    builds:
      - client
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format: zip

universal_binaries:
  - replace: true

release:
  draft: true
  prerelease: auto
  mode: append

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

