version: 2

builds:
  - id: windows
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X github.com/unblocked/chissl/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - windows
    goarch:
      - amd64
    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CC=cl.exe

archives:
  - format: binary
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

