# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chissl < Formula
  desc "HTTPS reverse tunnel server/client"
  homepage "https://github.com/unblocked/chissl"
  version "2.0"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/unblocked/chissl/releases/download/v2.0/chissl_Darwin_x86_64.zip"
    sha256 "bc78412645990403a5b696adbeda8a30b6548f7bbd11aca52a3105680df8b9b2"

    def install
      bin.install "chissl"
    end
  end
  on_arm do
    url "https://github.com/unblocked/chissl/releases/download/v2.0/chissl_Darwin_arm64.zip"
    sha256 "410c7d68e8f62b39a672c45ddeda32a9ac303541e561a86b1732f7707ebcd37a"

    def install
      bin.install "chissl"
    end
  end
end
