# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chissl < Formula
  desc "HTTPS reverse tunnel server/client"
  homepage "https://github.com/unblocked/chissl"
  version "2.0"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/unblocked/chissl/releases/download/v2.0/chissl_Darwin_x86_64.zip"
    sha256 "ac0c09e892c87ebb438d791998b9375f150cfbaf74da317a8efa97751933f581"

    def install
      bin.install "chissl"
    end
  end
  on_arm do
    url "https://github.com/unblocked/chissl/releases/download/v2.0/chissl_Darwin_arm64.zip"
    sha256 "a4653251f7afe32eaf0d70b98a0cb24a5f5a8fec768a8b64f8557d6db17ec547"

    def install
      bin.install "chissl"
    end
  end
end
