# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chissl < Formula
  desc "HTTPS reverse tunnel server/client"
  homepage "https://github.com/unblocked/chissl"
  version "2.0"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/unblocked/chissl/releases/download/v2.0/chissl_Darwin_x86_64.zip"
    sha256 "37361794cc33076c7c1e19ab001961660e81803d97911d7089b28444a93917a3"

    def install
      bin.install "chissl"
    end
  end
  on_arm do
    url "https://github.com/unblocked/chissl/releases/download/v2.0/chissl_Darwin_arm64.zip"
    sha256 "f67c414805216a0c75142b27703dccf482adae07531690896a4a2f31658d92c6"

    def install
      bin.install "chissl"
    end
  end
end
